"""
pr_creator/welcome_pr.py — Welcome PR Generator (V2, multi-tenant)

HOW IT WORKS:
─────────────
When RepoMind is INSTALLED on a new repository, we open a "welcome" PR that:

1. Adds `.repomind.yml` to the repo with SAFE defaults (mode: dry_run + hitl).
2. Adds a `.repomind/README.md` explaining the three modes.
3. Has a friendly PR body explaining what RepoMind is and how to opt in.

WHY:
    Before V2, a freshly-installed repo had NO indication that RepoMind
    existed. Users only found out when something broke or a PR appeared
    out of nowhere. The welcome PR makes the relationship EXPLICIT — the
    user sees us before we do anything that affects their code.

SAFETY:
    The welcome PR ONLY adds new files (`.repomind.yml`, `.repomind/README.md`).
    It never modifies existing code. Defaults are `mode: dry_run` so even
    if the user never reviews the PR, we won't surprise them with auto-PRs.

MULTI-TENANCY (V2):
    The webhook payload's `installation.id` is threaded down here so we
    authenticate as the CORRECT install (not the dev/env-var default).
    Without this, installing the App on a second GitHub account would
    return 403 "Resource not accessible by integration".

COMMUNICATION:
─────────────
webhook/webhook_handler.py routes `installation` and `installation_repositories`
events here. We open one welcome PR per newly-installed repo.
"""

from typing import Dict, Any, Optional

from shared.github_auth import get_github_client
from shared.repomind_config import generate_sample_yml
from shared.logger import get_logger

logger = get_logger("pr_creator.welcome_pr")


WELCOME_README = """\
# RepoMind on this repository

This repo has [RepoMind](https://github.com/repomind) — an autonomous CI
auto-fix agent — installed.

## What does it do?

When a GitHub Actions workflow on this repo **fails**, RepoMind:

1. Downloads the failure logs.
2. Runs a multi-agent LLM pipeline to triage the failure.
3. Proposes a fix.
4. Either posts the fix as a comment (`dry_run`) or opens a PR (`auto_fix`).
5. Waits for **a human to review and approve** before any merge.

## How is it configured?

This repo's `.repomind.yml` (in the repo root) controls the agent's behaviour
**for this repo specifically**. You don't need to email anyone to change it —
just edit the YAML and merge.

### Three modes

| Mode | What happens |
|------|--------------|
| `disabled` | RepoMind ignores this repo entirely. |
| `dry_run`  | RepoMind posts comments with proposed fixes. **Never opens PRs.** ← default |
| `auto_fix` | RepoMind opens fix PRs automatically. **Still requires human merge.** |

### Human-in-the-loop

`hitl_required: true` (the default) means RepoMind will **never auto-merge**
a PR. You always get the final say.

## Removing RepoMind

Delete `.repomind.yml`, or set `mode: disabled`, or uninstall the GitHub App
from this repo. There's nothing to clean up.

## Questions?

See the [onboarding guide](https://github.com/repomind/repomind/blob/main/projectdocs/ONBOARDING.md).
"""


WELCOME_PR_BODY = """\
# 👋 Welcome to RepoMind!

I'm an autonomous CI auto-fix agent. You (or someone with admin rights) just
installed me on this repository.

This PR adds **two files** to introduce me without changing any of your code:

- `.repomind.yml` — controls how I behave for this repo (safe defaults).
- `.repomind/README.md` — quick reference on what I do.

## Safe defaults

The `.repomind.yml` shipped here has:

- `mode: dry_run` → I'll post **comments** with proposed fixes, **not PRs**.
- `hitl_required: true` → I'll **never** auto-merge anything, ever.
- A small allowlist of low-risk failure types (deps, imports, syntax).

## What you should do

1. **Read the YAML.** It's commented and self-explanatory.
2. **Merge this PR** to opt in.
3. (Optional) Change `mode: dry_run` → `mode: auto_fix` once you trust me.

## What you should NOT worry about

- I will never push to `main` directly.
- I will never auto-merge a PR (with `hitl_required: true`).
- I will never modify a file outside the allowlist in `.repomind.yml`.

If you don't want me here, **close this PR** and uninstall the GitHub App.
I'll leave gracefully.

---
_Generated by RepoMind · V2 · Welcome flow_
"""


class WelcomePRCreator:
    """Opens the introductory PR on newly-installed repos."""

    BRANCH_NAME = "repomind/welcome"
    YML_PATH = ".repomind.yml"
    README_PATH = ".repomind/README.md"

    def create_welcome_pr(
        self,
        repo: str,
        installation_id: Optional[int] = None,
    ) -> Dict[str, Any]:
        """
        Open a welcome PR on the given repo. Idempotent — if a welcome PR
        already exists or the YAML is already there, we skip gracefully.

        Args:
            repo: Full repo name "owner/repo".
            installation_id: GitHub App install ID for this repo's account.
                             If None, falls back to env var (single-tenant).

        Returns:
            { "status": "created" | "skipped" | "failed", "url": str, ... }
        """
        try:
            gh = get_github_client(installation_id)
            repository = gh.get_repo(repo)
            base_branch = repository.default_branch

            # ── Idempotency: skip if .repomind.yml already exists ──
            try:
                repository.get_contents(self.YML_PATH, ref=base_branch)
                logger.info(
                    "welcome_pr_skipped_yml_exists", repo=repo
                )
                return {
                    "status": "skipped",
                    "reason": ".repomind.yml already exists in repo",
                    "url": None,
                }
            except Exception:
                pass  # Good — file doesn't exist, proceed.

            # ── Idempotency: skip if branch already exists ──
            try:
                repository.get_branch(self.BRANCH_NAME)
                logger.info("welcome_pr_skipped_branch_exists", repo=repo)
                return {
                    "status": "skipped",
                    "reason": f"Branch '{self.BRANCH_NAME}' already exists",
                    "url": None,
                }
            except Exception:
                pass  # Good — proceed to create branch.

            # ── Create branch off default ──
            base_ref = repository.get_git_ref(f"heads/{base_branch}")
            repository.create_git_ref(
                ref=f"refs/heads/{self.BRANCH_NAME}",
                sha=base_ref.object.sha,
            )
            logger.info("welcome_branch_created", repo=repo)

            # ── Add .repomind.yml ──
            repository.create_file(
                path=self.YML_PATH,
                message="chore: add RepoMind config (.repomind.yml)",
                content=generate_sample_yml(),
                branch=self.BRANCH_NAME,
            )

            # ── Add .repomind/README.md ──
            repository.create_file(
                path=self.README_PATH,
                message="chore: add RepoMind README",
                content=WELCOME_README,
                branch=self.BRANCH_NAME,
            )

            # ── Open PR ──
            pr = repository.create_pull(
                title="🤖 Welcome to RepoMind — review the config to opt in",
                body=WELCOME_PR_BODY,
                head=self.BRANCH_NAME,
                base=base_branch,
            )

            try:
                pr.add_to_labels("repomind", "welcome")
            except Exception:
                pass  # Labels might not exist — non-fatal

            logger.info(
                "welcome_pr_created",
                repo=repo,
                pr_url=pr.html_url,
                pr_number=pr.number,
            )
            return {
                "status": "created",
                "url": pr.html_url,
                "number": pr.number,
                "branch": self.BRANCH_NAME,
            }

        except Exception as e:
            logger.error("welcome_pr_failed", repo=repo, error=str(e))
            return {
                "status": "failed",
                "url": None,
                "reason": str(e),
            }